# Generated by Django 2.1.7 on 2019-04-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='engine_size',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
