# Generated by Django 2.1.7 on 2019-04-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190404_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='realtors',
            new_name='realtor',
        ),
    ]
